### ISSUE TITLE
提交时，提示服务器错误。

### ISSUE THREAD

**Issue by NianBroken** [DuckBurnIncense/short_link#1]
![image](https://user-images.githubusercontent.com/57057288/223993659-0e8ade05-751b-4c59-9a5c-ab430ba334b5.png)
![image](https://user-images.githubusercontent.com/57057288/223992693-b9a03413-c87a-497b-9745-5252397a60f9.png)
![image](https://user-images.githubusercontent.com/57057288/223992896-bc34ab35-611b-4bfd-b80a-be21477e9466.png)
![image](https://user-images.githubusercontent.com/57057288/223992764-42b7ce18-4225-4aa9-8ffd-041c48ba01d6.png)
![image](https://user-images.githubusercontent.com/57057288/223993272-9dd454a1-502f-4120-8663-bff3db11c161.png)

**Comment by DuckBurnIncense** [comment]
如果你使用的是 nginx (而非 apache), 请在 `nginx.conf` 中这样配置:

```
location / {
    try_files $uri $uri/ /api/index.php;
}
```

**Comment by DuckBurnIncense** [comment]
记得改数据库密码, GitHub issue 的 edit 是能看到历史记录的
