### ISSUE TITLE
设置访问密码后提示服务器错误

### ISSUE THREAD

**Issue by NianBroken** [DuckBurnIncense/short_link#2]
![image](https://user-images.githubusercontent.com/57057288/224489673-dcf6d497-f367-43c8-aa6c-15b5166aae34.png)
![image](https://user-images.githubusercontent.com/57057288/224489687-c41922e2-b681-4a0b-85ca-17972ae5a5b6.png)

**Comment by DuckBurnIncense** [comment]
奇怪的 bug 增加了, 好像是服务器没有正确接收到 `password` 参数导致的, 麻烦您把 `/api/RecordController.php` 的27行注释掉并在28行添加 `echo '"'.$input_password.'"';`, 我看看是怎么回事, 谢谢

![image](https://user-images.githubusercontent.com/87637270/224490337-24950b74-d175-4f2e-8ae5-4144d4f45417.png)

**Comment by DuckBurnIncense** [comment]
![image](https://user-images.githubusercontent.com/87637270/224490776-0be5ecff-406a-4982-965f-6254b802ae78.png)

确实是服务器没有正确接收到 `password` 参数导致的, 我也不知道怎么回事, 可以请您把28行改成 `var_dump($_GET);` 我再看看吗

![image](https://user-images.githubusercontent.com/87637270/224490866-79feb9ac-0518-4484-80ad-c27924cb0017.png)

**Comment by DuckBurnIncense** [comment]
> 或者我这边通过邮件给您发送我宝塔的临时管理链接，您帮我看看，您看可以吗？

可以, 这样就方便了, 谢谢

**Comment by DuckBurnIncense** [comment]
抱歉, 是我之前给的 nginx 配置有误, 漏掉了 `?$query_string`, 现在已经修改好, 可以正常使用了

![image](https://user-images.githubusercontent.com/87637270/224491619-7ac89b0d-50d3-4818-867a-66f1d8384741.png)
