### ISSUE TITLE
服务器错误

### ISSUE THREAD

**Issue by oceanuse** [DuckBurnIncense/short_link#3]
![image](https://user-images.githubusercontent.com/31952574/224490231-09c42f7c-a8c2-471c-b2b5-e23f9588c00e.png)

很喜欢你的[short_link]，可否做成docker，让更多像我一样的小白，可以简单的使用。
错误: 服务器错误是什么情况？请问该怎么配置，可否在相近点。
谢谢~~

**Comment by DuckBurnIncense** [comment]
说实话, docker 我不会用 （；´д｀）ゞ 主要是我目前还没有这个需求, 所以暂时不会把这个项目做成docker

至于 "服务器错误", 麻烦提供更详细的信息, 比如浏览器开发者工具的网络选项卡的截图, 或者直接提供您网站的网址我来测试

**Comment by oceanuse** [comment]
![image](https://user-images.githubusercontent.com/31952574/224551715-8ba1e5a5-5fa0-48f4-bb8d-694cadabdb94.png)
感觉是我数据库链接的问题

**Comment by DuckBurnIncense** [comment]
![image](https://user-images.githubusercontent.com/87637270/224551879-5a6c478d-5929-472e-ae63-07bbe174337e.png)

似乎不是数据库的原因, 而是 `.htaccess` 配置文件中的路径重写没生效导致的, 建议排查下你的 Apache 配置文件 (`httpd.conf`) 中的 `AllowOverride` 选项是否设置成了 `None` (应该要设置成 `All`)

![image](https://user-images.githubusercontent.com/87637270/224552368-8fb0032e-ecd9-44ad-9fbe-cedf58a5f1db.png)

**Comment by oceanuse** [comment]
是我Apache 配置的问题
已经好了，谢谢！
